baseurl: /
CanonifyURLs: yes
RelativeURLs: yes
theme: hugo-xmin
title: Blog of Wenqi Diao
disqusShortname: ''
footnotereturnlinkcontents: ↩
googleAnalytics: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
languageCode: en-us
enableEmoji: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
menu:
  main:
    - name: 主页
      url: ''
      weight: 1
    - name: 关于
      url: about/
      weight: 2
    - name: 博客
      url: post/
      weight: 3
    - name: 分类
      url: categories/
      weight: 4
    - name: 标签
      url: tags/
      weight: 5
params:
  description: Blog of Wenqi Diao
  footer: '&copy; Wenqi Diao 2020 -- 2025 | [Github](https://github.com/wdiao-zju/home)
    | [Twitter](https://twitter.com/DiaoWenqi)'
permalinks:
  post: /post/:year/:month/:day/:slug/
